# Generated by Django 5.0.3 on 2024-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('user', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=100)),
            ],
        ),
    ]
