# Generated by Django 5.0.3 on 2024-04-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_note_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(upload_to='notes/'),
        ),
    ]
