# Generated by Django 5.0.4 on 2024-04-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_note_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student_regno',
            field=models.ForeignKey(limit_choices_to={'user': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
    ]
